### ISSUE TITLE
Grid Issues

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/dsn1676-assignment-one#2]
@thomasjbradley

![screen shot 2015-01-11 at 7 17 32 pm](https://cloud.githubusercontent.com/assets/6373198/5697714/a3e71528-99c6-11e4-9d8b-679e223a7055.png)

All units are 1/3 of the screen at this size but the center unit looks more like 1/6 and it also pushes the last unit to the next row.

``` html
<div class="grid pad-top">
            <div class="unit unit-xs-1 unit-s-1 unit-m-1-3 unit-l-1-3 gutter-1-2">
                <img class="img-flex border push" src="artwork/shot_two.jpg" alt="Mugshot 1">
            </div>
    <div class="island">
    <div class="unit unit-xs-1 unit-s-1 unit-m-1-3 unit-l-1-3 brown island-1-2 ">
        <img src="artwork/hat.svg" class="logo2">
        <h2 class="center push-0 zetta white">Reward</h2>
        <h2 class="center push-0 zetta pad-bottom white">50 000</h2>
        <p class="center gutter-1-2 tera white">Wanted for the following crimes;</p>
        <ul class="nav white">
            <li><a class="island-1-2">Space piracy</a></li>
            <li><a class="island-1-2">Illegal asteroid mining</a></li>
            <li><a class="island-1-2" >Galactic treason</a></li>
        </ul>
        <img src="artwork/cuffs.svg" alt="cuffs" class="logo2">
    </div>
    </div>
    </div>
```

**Comment by thomasjbradley** [comment]
The `.island` `div` here, should be inside the `.unit` `div`:
https://github.com/valeriebordeleau/dsn1676-assignment-one/blob/gh-pages/index.html#L24

Only `.unit` elements can be directly inside the `.grid` `div`.

**Comment by valeriebordeleau** [comment]
![screen shot 2015-01-11 at 8 19 32 pm](https://cloud.githubusercontent.com/assets/6373198/5697991/33557ba2-99cf-11e4-86ab-1af206b1b070.png)

Thanks, that fixed the sizing. What might be making the second image go on the next line?

**Comment by thomasjbradley** [comment]
It appears to be inside its own grid, here:
https://github.com/valeriebordeleau/dsn1676-assignment-one/blob/gh-pages/index.html#L40

So, it cannot be on the same line.

**Comment by valeriebordeleau** [comment]
That solved it. Thanks
